version: "3"
services:
    mysqldb:
        image: mysql:8
        networks:
            - gamesys-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootroot
            - MYSQL_DATABASE=tweets
            - MYSQL_USER=myapp-root
            - MYSQL_PASSWORD=rootroot

    gamesys-spring-boot:
        image: gamesys-spring-boot
        ports:
            - "8070:8070"
        networks:
            - gamesys-mysql
        environment:
            - DATABASE_HOST=gamesys-mysql
            - DATABASE_USER=root
            - DATABASE_PASSWORD=rootroot
            - DATABASE_NAME=tweets
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/tweets?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC

        depends_on:
            - mysqldb
networks:
    gamesys-mysql:


