version: "3"
services:
    mysqldb:
        image: mysql:8
        networks:
            - gamesys-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootroot
            - MYSQL_DATABASE=tweet

    gamesys-spring-boot:
        image: gamesys-spring-boot
        ports:
            - "8070:8070"
        networks:
            - gamesys-mysql
        depends_on:
            - mysqldb



networks:
    gamesys-mysql: