version: '3.3'

services:
    #service 1: definition of mysql database
    db:
        image: mysql:latest
        container_name: mysql-db2
        environment:
            - MYSQL_ROOT_PASSWORD=rootroot
            - MYSQL_USER=root
        ports:
            - "3306:3306"
        restart: always

    #service 2: definition of your spring-boot app
    customerservice:                        #it is just a name, which will be used only in this file.
        image: gamesys-image               #name of the image after dockerfile executes
        container_name: gamesys-test-app  #name of the container created from docker image
        build:
            context: .                          #docker file path (. means root directory)
            dockerfile: Dockerfile              #docker file name
        ports:
            - "8070:8070"                       #docker container port with your os port
        restart: always

        depends_on:                           #define dependencies of this app
            - db                                #dependency name (which is defined with this name 'db' in this file earlier)
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://ljdbc:mysql://localhost:3306/tweets?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: rootroot